---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4
    run_list:
      - recipe[yum::default]

suites:
  - name: default
    run_list:
      - recipe[cassandra::default]
    attributes:
  - name: ring
    run_list:
      - recipe[cassandra::default]
    attributes: {
      "cassandra": {
        "ring": {
          "is_enabled": true,
          "seed": false,
          "size": 6,
          "node_position": 2
         }
       }
    }